### ISSUE TITLE
How to get Bank Name

### ISSUE THREAD

**Issue by heihitesh** [planetabhi/Banks-in-India#1]
Is their a way to also get bank names with the Image ?

**Comment by planetabhi** [comment]
Working on an update, and I'll release the new version in the next few days.

**Comment by planetabhi** [comment]
Not yet.

No definitive roadmap at this time, I plan to release the main dataset before v1.0. Current focus is on incorporating the remaining code types.

**Comment by planetabhi** [comment]
There you go [banks-in-india.json](https://github.com/planetabhi/banks-in-india/blob/main/datasets/banks-in-india.json)
